version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: my-next-app

    ports:
      - "3000:3000"

    env_file:
      - .env

    restart: unless-stopped

    depends_on:
      - redis

  redis:
    image: redis:7-alpine

    container_name: redis

    restart: unless-stopped

    ports:
      - "6379:6379"

    volumes:
      - redis-data:/data

volumes:
  redis-data: