type SummaryCardProps = {
  summary: string;
};

export default function SummaryCard({ summary }: SummaryCardProps) {
  return (
    <section className="rounded-3xl border border-gray-200 bg-white p-8 shadow-sm">
      <div className="mb-6 flex items-center gap-3">
        <div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-blue-100">
          <span className="text-2xl">🤖</span>
        </div>

        <div>
          <h2 className="text-2xl font-bold text-gray-900">
            AI Resume Summary
          </h2>

          <p className="text-sm text-gray-500">
            Overall evaluation generated by AI
          </p>
        </div>
      </div>

      <div className="rounded-2xl border border-blue-100 bg-blue-50 p-6">
        <p className="text-lg leading-8 text-gray-700">{summary}</p>
      </div>
    </section>
  );
}
